### ISSUE TITLE
My own proxy ratelimiting me

### ISSUE THREAD

**Issue by Hypurrnating** [halffalse/roproxy-lite#5]
When I run a piece of code that uses my proxy to get information from the API, I get 429, or sometimes 503
However when I copy the same link and use it in my browser it works fine. It baffles me

**Comment by askfalse** [comment]
That endpoint is very heavily rate limited by Roblox - you can alleviate it somewhat by passing along a cookie but this is otherwise expected behavior. You'll see similar results in an incognito window from a comparably trusted IP.

**Comment by Hypurrnating** [comment]
ofcourse. 
roblox at the root of every issue. ty tho
